Replace twisted with aiohttp
matrix-org/matrix-content-scanner-python pull request #39
Opened 2022-11-10 17:55 UTC by babolivier

I'm also using this as an opportunity to switch async test cases to `unittest`'s native async test case (since that's available as of Python 3.8), which fixes #38.

2022-11-11 18:18 UTC, squahtx requested changes
Looks good.

2022-11-14 10:42 UTC, babolivier commented on matrix_content_scanner/servlets/thumbnail.py
> +        # request.query is a multidict, however this isn't easily
Ah, this block is actually some poc I forgot to remove, thanks for pointing out!

2022-11-14 10:55 UTC, babolivier commented
I've also renamed the `servlets` module into `http` as "servlets" felt a bit antiquated a term to me and aiohttp uses "handlers" which is more in line with more recent web applications.

2022-11-14 11:01 UTC, babolivier commented
> I've also renamed the `servlets` module into `http` as "servlets" felt a bit antiquated a term to me and aiohttp uses "handlers" which is more in line with more recent web applications. Happy to revert if people feel unhappy about this decision.

Nevermind, actually it probably makes things more confusing when comparing with other projects of ours, and also causes conflicts and issues, so I've reverted that change.

2022-11-14 12:12 UTC, squahtx approved these changes

2022-11-14 13:59 UTC, merged